#
# (#)libs.versions.toml 0.3.0   07/07/2024
# (#)libs.versions.toml 0.2.0   06/30/2024
# (#)libs.versions.toml 0.1.0   06/27/2024
#
#  @author   Jonathan Parker
#  @version  0.3.0
#  @since    0.1.0
#
#  MIT License
#
#  Copyright (c) 2024 Jonathan M. Parker
#
#  Permission is hereby granted, free of charge, to any person obtaining a copy
#  of this software and associated documentation files (the "Software"), to deal
#  in the Software without restriction, including without limitation the rights
#  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
#  copies of the Software, and to permit persons to whom the Software is
#  furnished to do so, subject to the following conditions:
# 
#  The above copyright notice and this permission notice shall be included in all
#  copies or substantial portions of the Software.
#  
#  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
#  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
#  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
#  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
#  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
#  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

[versions]
ch-qos-logback-logback-classic = "1.5.6"
ch-qos-logback-logback-core = "1.5.6"
com-google-code-gson-gson = "2.10.1"
commons-cli-commons-cli = "1.8.0"
commons-codec-commons-codec = "1.17.0"
junit-junit = "4.13.2"
org-slf4j-slf4j-api = "2.0.11"
org-slf4j-slf4j-ext = "2.0.11"

[libraries]
ch-qos-logback-logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "ch-qos-logback-logback-classic" }
ch-qos-logback-logback-core = { module = "ch.qos.logback:logback-core", version.ref = "ch-qos-logback-logback-core" }
com-google-code-gson-gson = { module = "com.google.code.gson:gson", version.ref = "com-google-code-gson-gson" }
commons-cli-commons-cli = { module = "commons-cli:commons-cli", version.ref = "commons-cli-commons-cli" }
commons-codec-commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec-commons-codec" }
junit-junit = { module = "junit:junit", version.ref = "junit-junit" }
org-slf4j-slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "org-slf4j-slf4j-api" }
org-slf4j-slf4j-ext = { module = "org.slf4j:slf4j-ext", version.ref = "org-slf4j-slf4j-ext" }
